import DOMPurify from 'dompurify';

export function sanitizeHtml(html: string): string {
  if (typeof window === 'undefined') {
    return html
      .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '')
      .replace(/<script\b[^>]*\/?>/gi, '')
      .replace(/href\s*=\s*(?:"javascript:[^"]*"|'javascript:[^']*')/gi, '')
      .replace(/src\s*=\s*(?:"javascript:[^"]*"|'javascript:[^']*')/gi, '')
      .replace(/\son[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, '');
  }
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'p',
      'br',
      'hr',
      'pre',
      'code',
      'blockquote',
      'ul',
      'ol',
      'li',
      'strong',
      'em',
      'b',
      'i',
      'u',
      's',
      'mark',
      'sub',
      'sup',
      'a',
      'img',
      'figure',
      'figcaption',
      'table',
      'thead',
      'tbody',
      'tr',
      'th',
      'td',
      'div',
      'span',
      'section',
      'article',
      'aside',
      'header',
      'footer',
      'details',
      'summary',
      'dl',
      'dt',
      'dd',
      'abbr',
      'cite',
      'q',
      'del',
      'ins',
      'ruby',
      'rt',
      'rp',
      'sup',
      'sub',
      'input',
      'label',
    ],
    ALLOWED_ATTR: [
      'href',
      'src',
      'alt',
      'title',
      'width',
      'height',
      'class',
      'id',
      'style',
      'target',
      'rel',
      'colspan',
      'rowspan',
      'scope',
      'type',
      'checked',
      'disabled',
      'value',
      'placeholder',
      'open',
      'data-*',
    ],
    ALLOW_DATA_ATTR: true,
  });
}
