export type AddressDictionaryEntry = readonly [source: string, target: string];

export const ADDRESS_NAME_ENTRIES: readonly AddressDictionaryEntry[] = [
  ['جمهوری اسلامی ایران', 'Islamic Republic of Iran'],
  ['کهگیلویه و بویراحمد', 'Kohgiluyeh and Boyer-Ahmad'],
  ['سیستان و بلوچستان', 'Sistan and Baluchestan'],
  ['چهارمحال و بختیاری', 'Chaharmahal and Bakhtiari'],
  ['آذربایجان شرقی', 'East Azerbaijan'],
  ['آذربایجان غربی', 'West Azerbaijan'],
  ['خراسان رضوی', 'Razavi Khorasan'],
  ['خراسان شمالی', 'North Khorasan'],
  ['خراسان جنوبی', 'South Khorasan'],
  ['شهرک غرب', 'Shahrak-e Gharb'],
  ['ده ونک', 'Deh-e Vanak'],
  ['میدان ونک', 'Vanak Square'],
  ['سعادت آباد', 'Saadat Abad'],
  ['جنت آباد', 'Jannat Abad'],
  ['گنبد کاووس', 'Gonbad-e Kavus'],
  ['بندر عباس', 'Bandar Abbas'],
  ['بندر انزلی', 'Bandar Anzali'],
  ['بندر ماهشهر', 'Bandar Mahshahr'],
  ['بندر بوشهر', 'Bandar Bushehr'],
  ['شاهین شهر', 'Shahin Shahr'],
  ['اسلام شهر', 'Eslamshahr'],
  ['خرم آباد', 'Khorramabad'],
  ['خرم دره', 'Khorramdarreh'],
  ['قائم شهر', 'Qaemshahr'],
  ['نجف آباد', 'Najafabad'],
  ['خمینی شهر', 'Khomeinishahr'],
  ['ولی عصر', 'Valiasr'],
  ['امام خمینی', 'Imam Khomeini'],
  ['امام رضا', 'Imam Reza'],
  ['گلستان جنوبی', 'South Golestan'],
  ['گلستان شمالی', 'North Golestan'],
  ['ایرانشهر', 'Iranshahr'],
  ['شهرکرد', 'Shahrekord'],
  ['تهران', 'Tehran'],
  ['اصفهان', 'Isfahan'],
  ['فارس', 'Fars'],
  ['خوزستان', 'Khuzestan'],
  ['البرز', 'Alborz'],
  ['اردبیل', 'Ardabil'],
  ['ایلام', 'Ilam'],
  ['بوشهر', 'Bushehr'],
  ['زنجان', 'Zanjan'],
  ['سمنان', 'Semnan'],
  ['قزوین', 'Qazvin'],
  ['قم', 'Qom'],
  ['کردستان', 'Kurdistan'],
  ['کرمان', 'Kerman'],
  ['کرمانشاه', 'Kermanshah'],
  ['گلستان', 'Golestan'],
  ['گیلان', 'Gilan'],
  ['لرستان', 'Lorestan'],
  ['مازندران', 'Mazandaran'],
  ['مرکزی', 'Markazi'],
  ['هرمزگان', 'Hormozgan'],
  ['همدان', 'Hamedan'],
  ['یزد', 'Yazd'],
  ['شیراز', 'Shiraz'],
  ['مشهد', 'Mashhad'],
  ['تبریز', 'Tabriz'],
  ['کرج', 'Karaj'],
  ['اهواز', 'Ahvaz'],
  ['رشت', 'Rasht'],
  ['اراک', 'Arak'],
  ['ساری', 'Sari'],
  ['گرگان', 'Gorgan'],
  ['سنندج', 'Sanandaj'],
  ['زاهدان', 'Zahedan'],
  ['بجنورد', 'Bojnord'],
  ['یاسوج', 'Yasuj'],
  ['بیرجند', 'Birjand'],
  ['کاشان', 'Kashan'],
  ['کیش', 'Kish'],
  ['قشم', 'Qeshm'],
  ['ورامین', 'Varamin'],
  ['پاکدشت', 'Pakdasht'],
  ['پردیس', 'Pardis'],
  ['پرند', 'Parand'],
  ['شهریار', 'Shahriar'],
  ['ملارد', 'Malard'],
  ['قدس', 'Qods'],
  ['دزفول', 'Dezful'],
  ['آبادان', 'Abadan'],
  ['خرمشهر', 'Khorramshahr'],
  ['بابل', 'Babol'],
  ['آمل', 'Amol'],
  ['چالوس', 'Chalus'],
  ['لاهیجان', 'Lahijan'],
  ['انزلی', 'Anzali'],
  ['ارومیه', 'Urmia'],
  ['مهاباد', 'Mahabad'],
  ['مراغه', 'Maragheh'],
  ['مرند', 'Marand'],
  ['کاشمر', 'Kashmar'],
  ['طبس', 'Tabas'],
  ['نهاوند', 'Nahavand'],
  ['ساوه', 'Saveh'],
  ['شاهرود', 'Shahroud'],
  ['دامغان', 'Damghan'],
  ['دماوند', 'Damavand'],
  ['فیروزکوه', 'Firuzkuh'],
  ['فردیس', 'Fardis'],
  ['اندیشه', 'Andisheh'],
  ['بهارستان', 'Baharestan'],
  ['سبزوار', 'Sabzevar'],
  ['نیشابور', 'Neyshabur'],
  ['مجیدیه', 'Majidiyeh'],
  ['نیاوران', 'Niavaran'],
  ['زعفرانیه', 'Zaferanieh'],
  ['قیطریه', 'Qeytarieh'],
  ['شهران', 'Shahran'],
  ['صادقیه', 'Sadeghiyeh'],
  ['ونک', 'Vanak'],
  ['پاسداران', 'Pasdaran'],
  ['بهشتی', 'Beheshti'],
  ['آزادی', 'Azadi'],
  ['انقلاب', 'Enqelab'],
  ['فاطمی', 'Fatemi'],
  ['مطهری', 'Motahari'],
  ['شریعتی', 'Shariati'],
  ['طالقانی', 'Taleghani'],
  ['کشاورز', 'Keshavarz'],
  ['زند', 'Zand'],
  ['جمهوری', 'Jomhouri'],
  ['کارگر', 'Kargar'],
  ['هاشمی', 'Hashemi'],
  ['گاندی', 'Gandhi'],
  ['ایران', 'Iran'],
  ['یاس', 'Yas'],
] as const;

export const ADDRESS_TERM_ENTRIES: readonly AddressDictionaryEntry[] = [
  ['نرسیده به', 'Before'],
  ['بعد از', 'After'],
  ['رو به روی', 'Opposite'],
  ['روبروی', 'Opposite'],
  ['بن بست', 'Dead End'],
  ['چهارراه', 'Crossroad'],
  ['بزرگراه', 'Highway'],
  ['اتوبان', 'Expressway'],
  ['خیابان', 'Street'],
  ['بلوار', 'Boulevard'],
  ['کوچه', 'Alley'],
  ['میدان', 'Square'],
  ['جاده', 'Road'],
  ['نبش', 'Corner of'],
  ['کنار', 'Next to'],
  ['جنب', 'Near'],
  ['پلاک', 'No.'],
  ['واحد', 'Unit'],
  ['طبقه', 'Floor'],
  ['محله', 'District'],
  ['استان', 'Province'],
  ['شهر', 'City'],
  ['ساختمان', 'Building'],
  ['مجتمع', 'Complex'],
  ['پاساژ', 'Shopping Center'],
  ['برج', 'Tower'],
  ['بانک', 'Bank'],
  ['بیمارستان', 'Hospital'],
  ['دانشگاه', 'University'],
  ['مدرسه', 'School'],
  ['مسجد', 'Mosque'],
  ['پارک', 'Park'],
  ['پل', 'Bridge'],
  ['شمالی', 'North'],
  ['جنوبی', 'South'],
  ['شرقی', 'East'],
  ['غربی', 'West'],
] as const;

export const ADDRESS_WORD_OVERRIDES: Readonly<Record<string, string>> = {
  شهید: 'Shahid',
  دکتر: 'Dr',
  مهندس: 'Eng',
  حاجی: 'Haji',
  سید: 'Seyed',
  اصلی: 'Main',
  فرعی: 'Sub',
  مرکزی: 'Central',
  جنوبی: 'South',
  شمالی: 'North',
  شرقی: 'East',
  غربی: 'West',
  غرب: 'West',
  شرق: 'East',
  شمال: 'North',
  جنوب: 'South',
  محمد: 'Mohammad',
  علی: 'Ali',
  حسن: 'Hassan',
  حسین: 'Hossein',
  رضا: 'Reza',
  مهدی: 'Mehdi',
  احمد: 'Ahmad',
  امیر: 'Amir',
  اکبر: 'Akbar',
  اصغر: 'Asghar',
  زهرا: 'Zahra',
  فاطمه: 'Fatemeh',
  مریم: 'Maryam',
  بانک: 'Bank',
};

export const PRODUCTIVE_SUFFIXES: readonly AddressDictionaryEntry[] = [
  ['آبادی', 'abadi'],
  ['زاده', 'zadeh'],
  ['نژاد', 'nejad'],
  ['آباد', 'abad'],
  ['ستان', 'stan'],
  ['پور', 'pour'],
  ['دشت', 'dasht'],
  ['شهر', 'shahr'],
  ['رود', 'rud'],
  ['کوه', 'kuh'],
] as const;

export const PERSIAN_TRANSLITERATION_MAP: Readonly<Record<string, string>> = {
  آ: 'a',
  ا: 'a',
  ب: 'b',
  پ: 'p',
  ت: 't',
  ث: 's',
  ج: 'j',
  چ: 'ch',
  ح: 'h',
  خ: 'kh',
  د: 'd',
  ذ: 'z',
  ر: 'r',
  ز: 'z',
  ژ: 'zh',
  س: 's',
  ش: 'sh',
  ص: 's',
  ض: 'z',
  ط: 't',
  ظ: 'z',
  ع: 'a',
  غ: 'gh',
  ف: 'f',
  ق: 'q',
  ک: 'k',
  گ: 'g',
  ل: 'l',
  م: 'm',
  ن: 'n',
  و: 'v',
  ه: 'h',
  ی: 'y',
  ئ: 'y',
  ء: 'a',
  ة: 'h',
};
