import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const ARTICLE_PATH = 'content/blog/2026-06-24-loan-1405-guide.md';
const TARGET_TITLE = 'جدول اقساط وام مسکن ملی ۱۴۰۵ | سقف ۸۵۰ میلیون و شرایط';
const TARGET_DESCRIPTION =
  'جدول نمونه اقساط وام مسکن ملی ۱۴۰۵ با سقف ۸۵۰ میلیون تومان برای پروژه‌های مشمول، شرایط دریافت و روش محاسبه قسط. مبلغ واقعی طبق قرارداد بانکی است.';

const readArticle = () => fs.readFileSync(path.join(process.cwd(), ARTICLE_PATH), 'utf8');

describe('loan 1405 GSC intent and financial-content correctness contract', () => {
  it('matches the zero-click GSC intent with a useful title and SERP description', () => {
    const article = readArticle();

    expect(article).toContain(`title: '${TARGET_TITLE}'`);
    expect(article).toContain(`description: '${TARGET_DESCRIPTION}'`);
    expect(TARGET_DESCRIPTION.length).toBeGreaterThanOrEqual(90);
    expect(TARGET_DESCRIPTION.length).toBeLessThanOrEqual(160);
    expect(article).toContain("'جدول اقساط وام مسکن ملی ۱۴۰۵'");
  });

  it('updates the National Housing Movement ceiling and eligibility instead of keeping stale claims', () => {
    const article = readArticle();

    expect(article).toContain('۸۵۰ میلیون تومان');
    expect(article).toContain('پیشرفت فیزیکی بیش از ۶۵ درصد');
    expect(article).not.toContain('نرخ سود**: ۷-۹٪');
    expect(article).not.toContain('سقف وام**: تا ۵۵۰ میلیون تومان');
    expect(article).not.toContain('پیش‌پرداخت**: حداقل ۳۰٪ قیمت ملک');
  });

  it('labels installment figures as illustrative and keeps the bank contract authoritative', () => {
    const article = readArticle();

    expect(article).toContain('نمونه محاسباتی');
    expect(article).toContain('قرارداد بانکی ملاک است');
    expect(article).toContain('فرض نرخ سالانه ۱۸٪');
    expect(article).toContain('۱۳,۱۱۸,۱۴۸');
    expect(article).toContain('/loan');
  });

  it('replaces malformed autogenerated FAQs with user-facing questions', () => {
    const article = readArticle();

    expect(article).toContain("question: 'سقف وام نهضت ملی مسکن در ۱۴۰۵ چقدر است؟'");
    expect(article).toContain("question: 'قسط وام ۸۵۰ میلیونی نهضت ملی مسکن چقدر می‌شود؟'");
    expect(article).not.toContain("question: 'چگونه خرید مسکن");
  });
});
